graph TD
    Database --- MenuRepository
    Database --- InventoryRepository
    MenuRepository --- Menu
    InventoryRepository --- Inventory
    Waiter --- Client
    Waiter --- Order
    Waiter --- Inventory
    Waiter --- Check
    Client --- Order
    Order --- Item
    Inventory --- Item
    Check --- Item
    Check --- Menu