sequenceDiagram
    actor Client
    actor Waiter
    participant Order
    participant Inventory
    participant Item
    participant Check
    participant Menu

    Waiter->>Client: greet()
    Client->>Waiter: greet()
    Client->>Item: select(pizza)
    Client->>Order: add_item(item)
    Client->>Waiter: place_order(order)
    Waiter->>Inventory: check_availability(item)
    Inventory-->>Waiter: available!
    Waiter->>Order: execute_order()
    Waiter-->>Client: confirmed!
    Client->>Waiter: ask_for_check()
    Waiter->>Check: calculate_amount(items, menu)
    Check-->>Waiter: total amount
    Waiter->>Client: give_check(check)